name: Run code on server
run-name: Run tests

on:
  workflow_dispatch:
    inputs:
      branch:
        - main

concurrency:
  cancel-in-progress: true

jobs:
  Run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Setup NodeJS
        uses: actions/setup-node@v3
      
      - name: Install dependencies
        run: npm i
      
      - name: Run tests
        run: npm run codeceptjs:headless