name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      HEADLESS: true
      
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npx codeceptjs run --reporter mochawesome

      - name: Publish test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: output
